# -*- coding: utf-8 -*-
{
    'name': 'Financimiento de Créditos',
    'summary': """
    Modulo para gestionar el crédito para un prestamo
    """,
    'author': 'Craulyn Feliz,Jeffry J. De La Rosa, Gregory Burgos',
    'category':'General',
    'version':'17.0.0.12',
    'depends': [
        'base',
        'web',
        'sale',
        'mail',
        'contacts',
        'hr',
        'sale_stock',
        'cjg_finance_pos',
    ],
    'data':[
        'data/sale_credit_category_data.xml',
        'data/collection_notice_sequence.xml',
        'security/credito_security.xml',
        'security/credito_documentation_security.xml',  # FIX: Grupo Documentación (María Santana)
        'security/ir.model.access.csv',
        'security/sale_credit_security.xml',
        # Load view definitions BEFORE menus that reference them
        'views/assets.xml',
        'views/credit_report.xml',
        'views/res_config_setting_view.xml',
        'views/sale_credit_adjustment_views.xml',
        'views/cash_box_closing_views.xml',
        'views/menu_view.xml',
        'views/sale_credit_view.xml',
        'views/sale_credit_testarossa_parity_views.xml',
        'views/sale_credit_collection_notice_views.xml',
        'reports/sale_credit_collection_notice_report.xml',
        'data/ir_sequence_data.xml',
        'data/data.xml',
        'data/product.xml',
        'data/cron.xml',
        'reports/template_payment_report.xml',
        'reports/termica_invoice.xml',
        'reports/reports_sale_credit_payment.xml',
        'reports/bounced_check_receipt.xml',
        'reports/cash_box_closing_report.xml',
        'reports/sale_credit_report.xml',
        'reports/sale_credit_process_report.xml',
        'views/sale_credit_category_view.xml',
        'views/sale_credit_installment_view.xml',
        'views/sale_credit_frequency_view.xml',
        'views/sale_credit_payment.xml',
        'views/sale_credit_payment_parity_views.xml',
        'wizards/maintenance_exchange_rate_wizard.xml',
        'wizards/maintenance_period_generate.xml',
        'views/maintenance_contract_views.xml',
        'views/sale_credit_charge_views.xml',
        'views/pos_integration_views.xml',
        'views/pos_payment_receipt_ext_views.xml',  # Extensión de recibos POS para créditos
        # 'views/sale_credit_view_legacy.xml',  # Commented - has payment_date field error
        'views/sale_credit_portfolio_views.xml',
        'views/res_company_views.xml',
        'views/agreement_template_views.xml',
        'views/res_partner.xml',
        'views/res_partner_testarossa_parity_views.xml',
        'views/credit_overdue.xml',
        'views/sale_order_view.xml',
        'wizards/sale_credit_cancel_wizard.xml',
        'wizards/bounced_check_wizard_views.xml',
        'wizards/sale_credit_refuse_wizard.xml',
        'wizards/sale_credit_transfer_wizard.xml',
        'wizards/mora_exoneracion.xml',
        'wizards/sale_credit_cuztome.xml',
        'views/config_mora.xml',
        'views/credito_preaprobado.xml',
        'reports/maintenance_contract_report.xml',
        'reports/credit_statement_report.xml',
        'reports/monthly_portfolio_report.xml',
        'data/cron_jobs.xml',
        'data/cron_contract_processes.xml',
        'data/maintenance_period_cron.xml',
        'views/contract_dashboard_actions.xml',
        'views/sale_credit_planilla_views.xml',
        'views/finance_refinancing_history_views.xml',
        'views/sale_credit_process_views.xml',
        'wizards/sale_credit_refinance_wizard.xml',
        'wizards/sale_credit_reactivation_wizard.xml',
        'wizards/sale_credit_devolucion_wizard.xml',
        'wizards/sale_credit_mejora_wizard.xml',
        'wizards/sale_credit_reembolso_wizard.xml',
        'wizards/sale_credit_no_reembolso_wizard.xml',
        'wizards/cashbook_diary_wizard.xml',
        'wizards/massive_collection_notice_wizard.xml',
        'wizards/nc_process_wizard.xml',
        'wizards/partner_initial_payments_wizard.xml',
        'wizards/partner_payments_wizard.xml',
        'wizards/partner_payment_detail_wizard.xml',
        'wizards/balance_cuenta_wizard.xml',
        'wizards/balance_global_wizard.xml',
        'wizards/balance_movimiento_wizard.xml',
        'wizards/balance_index_wizard.xml',
        'wizards/ver_listado_cartera_wizard.xml',
        'wizards/ver_listado_cartera_v2_wizard.xml',
        'wizards/ver_listado_cartera_v3_wizard.xml',
        'wizards/ver_listado_saldos_wizard.xml',
        'wizards/generar_cierre_contable_wizard.xml',
        'views/cierre_contable_views.xml',
        'data/cierre_contable_demo.xml',
        # === Archivos agregados después del recorte del manifest (restaurado) ===
        'views/cjg_finance_status_aging_audit_views.xml',  # TRACK 3 (F10): vista del log aging
        # TRACK 8 (F7) y TRACK 9 (F8) — listados tree con XLSX
        'wizards/partner_initial_payments_tree_wizard.xml',
        'wizards/partner_payments_tree_wizard.xml',
        # TRACK 12 (F13) — sys_direccion_temp
        'views/sale_credit_direccion_temp_views.xml',
        # GAP-12.07: reporte Acta de Cierre / Finiquito
        'reports/sale_credit_finiquito_report_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'cjg_finance/static/src/css/dashboard_modern.css',
            'cjg_finance/static/src/js/finance_dashboard.js',
            'cjg_finance/static/src/xml/finance_dashboard.xml',
            'cjg_finance/static/src/scss/finance_dashboard.scss',
            'cjg_finance/static/src/js/partner_contract_tabs.js',
            'cjg_finance/static/src/xml/partner_contract_tabs.xml',
            # Contract Dashboard OWL Component
            'cjg_finance/static/src/components/contract_dashboard/contract_dashboard.js',
            'cjg_finance/static/src/components/contract_dashboard/contract_dashboard.xml',
            'cjg_finance/static/src/components/contract_dashboard/contract_dashboard.scss',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
}
